DROP DATABASE IF EXISTS primpsg;
CREATE DATABASE IF NOT EXISTS primpsg;
use primpsg;
CREATE TABLE images (
  id mediumint(9) NOT NULL AUTO_INCREMENT,
  SOPIUID varchar(128) NOT NULL,
  SIUID varchar(128) NOT NULL,
  NEWSOPIUID varchar(128) NOT NULL,
  ACCN varchar(64) DEFAULT NULL,
  IMAGENUM int(5) NOT NULL default 0,
  CREATED datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=348632 DEFAULT CHARSET=latin1;
